name: generate file
on:
  - push

jobs:
  generate:
    name: file generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: false
      - name: install fileadder
        run: GOBIN=$(pwd) GOPRIVATE=github.com/Qman11010101/fileadder" go install github.com/Qman11010101/fileadder@latest
      - name: run fileadder
        run: fileadder
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'generated'
          git push